### ISSUE TITLE
GCC verification is wrong for windows

### ISSUE THREAD

**Issue by datenreisender** [NordicSemiconductor/pc-nrfconnect-gettingstarted#16]
In https://github.com/NordicSemiconductor/pc-nrfconnect-gettingstarted/blob/720a514/resources/data/win_deps-0.9.4.json#L220-L223 we describe downloading and installing GCC 8 but in https://github.com/NordicSemiconductor/pc-nrfconnect-gettingstarted/blob/720a514/resources/data/win_deps-0.9.4.json#L231 it looks like on Windows we are verifying that GCC 7 is installed.

In https://github.com/NordicSemiconductor/pc-nrfconnect-gettingstarted/blob/720a514/resources/data/darwin_deps-0.9.3.json#L223 and https://github.com/NordicSemiconductor/pc-nrfconnect-gettingstarted/blob/720a514/resources/data/linux_zephyr_deps-0.9.5.json#L431 it looks like this should not be a problem for macOS and Linux.

**Comment by bencefr** [comment]
v1.0.5 has been published
